### PR TITLE
blindly applied yapf autofix

### PR DESCRIPTION
**Pull request by jspaaks**
; updated the github actions so it runs prospector

Initially, we hade more than 1600 errors, now ~~about 160 or so (excluding the ``tests/`` directory)~~ 142 (including the ``tests/`` directory). Noice!

### CODE REVIEW

**Comment by jspaaks** [comment]
Not green yet, but I think it's probably still a good idea for somebody to merge this now, because it is sort of blocking any other development.

Notify: @CunliangGeng @fdiblen

**Comment by CunliangGeng** [comment]
I have to say the linting test is quite strict and it's very hard to pass all. I agree to merge it now and leave this test for the very very last step to fix.

Better to skip this test currently. And fix the linting problems when refactoring code.

**Comment by jspaaks** [comment]
The errors that remain are the ones that need more work, for example (showing a subset here)

```
matchms/ms_similarity_classical.py
    pylint: pointless-string-statement / String statement has no effect

matchms/networking.py
  Line: 390
    pylint: too-many-nested-blocks / Too many nested blocks (6/5) (col 4)
    pylint: too-many-nested-blocks / Too many nested blocks (6/5) (col 4)
  Line: 778
    pylint: protected-access / Access to a protected member _sizes of a client class (col 8)

matchms/plotting_functions.py
  Line: 110
    pylint: redefined-builtin / Redefining built-in 'id' (col 11)
  Line: 324
    pylint: consider-using-enumerate / Consider using enumerate instead of iterating with range and len (col 4)
  Line: 374
    pylint: dangerous-default-value / Dangerous default value [] as argument
    pyflakes: F811 / redefinition of unused 'scour' from line 25 (col 1)
  Line: 625
    pylint: dangerous-default-value / Dangerous default value [] as argument

matchms/similarity_measure.py
  Line: 365
    pylint: too-many-arguments / Too many arguments (6/5) (col 4)
    pylint: too-many-locals / Too many local variables (19/15) (col 4)
    mccabe: MC0001 / SimilarityMeasures.get_vectors_centroid is too complex (17)
  Line: 597
    pylint: unsubscriptable-object / Value 'cdist.shape' is unsubscriptable (col 34)
```

**Comment by fdiblen** [comment]
@jspaaks @CunliangGeng great! I spent some time last night and ended up with the same list. These issues should be solved manually. I suggest to create a new issue for this. @florian-huber is this something you would like to work on?

**Comment by jspaaks** [comment]
> I have to say the linting test is quite strict and it's very hard to pass all. I agree to merge it now and leave this test for the very very last step to fix.
> 
> Better to skip this test currently. And fix the linting problems when refactoring code.

If we decide to adopt this layout (https://github.com/matchms/matchms/tree/20e72cca97919df7f08f3741e4d114623cd0a9c5/matchms), it should be pretty easy to exclude ``old-structure`` from being analyzed. That way, we can make sure that both the linting and the tests are always green as we proceed with moving functionality from ``old-structure/`` to the new structure.

**Comment by jspaaks** [comment]
> @jspaaks @CunliangGeng great! I spent some time last night and ended up with the same list. These issues should be solved manually. I suggest to create a new issue for this. @florian-huber is this something you would like to work on?

Sorry if I inadvertently duplicated your hard work @fdiblen!

**Comment by fdiblen** [comment]
It was your issue but I couldn't help myself while reviewing it. I tried autopep8, yapf, black and autoflake but ended up with the same number of issues. I also fixed some of them manually but it will require some time to solved them all which we should definitely do.

**Comment by florian-huber** [comment]
Hi guys,
I can work on solving the linting things mentioned above! That also gives me the chance to improve the most embarrassing code pieces myself ;)

**Comment by jspaaks** [comment]
> It was your issue but I couldn't help myself while reviewing it. I tried autopep8, yapf, black and autoflake but ended up with the same number of issues. I also fixed some of them manually but it will require some time to solved them all which we should definitely do.

I completely understand where you're coming from with this! :)

**Comment by florian-huber** [comment]
@fdiblen @CunliangGeng 
Since I already made some changes to the code in another branch (#43 ), maybe it would make sense to merge both pull requests to avoid confusion?

**Comment by fdiblen** [comment]
Sounds good to me. We can merge them and work on the remaining ones. Lets do this after the stand up.

**Comment by CunliangGeng** [comment]
Fine with me, too.

**Comment by jspaaks** [comment]
I merged Florian's changes and created #50.

**Pull request merged**
