### PR TITLE
14 conda

### LINKED ISSUE #12: Make a pip package of the software
See below link for a tutorial.
https://packaging.python.org/tutorials/packaging-projects/

### PR DESCRIPTION
**Pull request by fdiblen**
Please ignore Sonarcloud warnings.

This PR also includes changes from the master to solve the conflicts.
**Please test the the PR locally first!**
In a clean conda environment run:
`conda install -c conda-forge -c bioconda -c nlesc matchms`

This PR makes the following changes:
- Creates conda packages
- Pushes conda packages to anaconda cloud
- Pushes python packages to pypi
- Removes old Travis config
- Cleans up the package dependencies in 
  - meta.yml
  - environment.yml
  - setup.py

This PR adds conda packaging and deployment. 
Fixes: #12 #13 #14 #15 
and
https://github.com/NLeSC/python-template/issues/53

### CODE REVIEW

**Comment by jspaaks** [comment]
I'm calling that a success!

**Comment by fdiblen** [comment]
Finally all green :heavy_check_mark::heavy_check_mark:
Let's merge it before anything else breaks the the PR :neckbeard:

**Comment by jspaaks** [comment]
@fdiblen This may help with the sonarcloud checks https://github.com/matchms/matchms/pull/80

**Comment by HannoSpreeuw** [comment]
Running the command 
`conda install -c conda-forge -c bioconda -c nlesc matchms`
on both my laptop and pc. Both are still busy after half an hour:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for bokeh pytest-doctestplus matplotlib mkl-service h5py numba numpy pytest-arraydiff scikit-learn mkl_random pyta
```
I'll keep you updated.

**Comment by jspaaks** [comment]
Could be because of our strict version pinning

**Comment by fdiblen** [comment]
It takes about 7-8 minutes for github to build it. It is almost the same on my laptop.

**Comment by HannoSpreeuw** [comment]
It completed on my pc, not sure it worked.

https://pastebin.com/gQuinCT6
https://pastebin.com/BSSb27GF

**Comment by HannoSpreeuw** [comment]
Also completed on my laptop.
Similar or the same output.
Same anaconda version as my pc.
`python -c "import matchms"` gives
```
(base) [hanno@mysuperfriendlyhost ~]$ python -c "import matchms"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'matchms'
```

**Comment by fdiblen** [comment]
> Also completed on my laptop.
> Similar or the same output.
> Same anaconda version as my pc.
> `python -c "import matchms"` gives
> 
> ```
> (base) [hanno@mysuperfriendlyhost ~]$ python -c "import matchms"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'matchms'
> ```

I have just tested and it works fine on my machine. The installation took 2m 55s. 
These are the commands I executed to install:
```
conda create -n temp python=3.7 -y
conda activate temp
conda install -c conda-forge -c bioconda -c nlesc matchms
```

Testing the import:
```
$ python                                                                                                                    (temp) 
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matchms
>>> dir(matchms)
['Scores', 'Spectrum', '__all__', '__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'calculate_scores', 'logging']
>>>
```

**Review by jspaaks — APPROVED** [review]
I think this can be merged. My reasoning is as follows:

for some files, we can see that they work
- ci_build
- ci_deploy_anaconda
- prospector
- sonarcloud
- README.rst

Others can simply be ignored for this PR
- matchms/similarity/spec2vec

So that leaves: 
- environment.yml: tested by conda env create, takes 2 minutes or so 
- setup.py

meta.yml: seems to be working https://anaconda.org/nlesc/repo?type=conda&label=main

Couple of points:

- Is ci_deploy_pypi supposed to be working? I don't see anything on PyPI
- pip itself needs to be added to environment.yml


I also did
```
cd $(mktemp -d)
```

made a file envrionment.yml there, with 
```
name: matchms
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - matchms
```

in it.

Then I did ``conda env create``, which worked.

**Comment by fdiblen** [comment]
> I think this can be merged. My reasoning is as follows:
> 
> for some files, we can see that they work
> 
> * ci_build
> * ci_deploy_anaconda
> * prospector
> * sonarcloud
> * README.rst
> 
> Others can simply be ignored for this PR
> 
> * matchms/similarity/spec2vec
> 
> So that leaves:
> 
> * environment.yml: tested by conda env create, takes 2 minutes or so
> * setup.py
> 
> meta.yml: seems to be working https://anaconda.org/nlesc/repo?type=conda&label=main
> 
> Couple of points:
> 
> * Is ci_deploy_pypi supposed to be working? I don't see anything on PyPI
> * pip itself needs to be added to environment.yml

Thanks for the review @jspaaks!

I added pip to environment.yml
In principle pypi deployment should work. We need to get a token using nlesc account. @sverhoeven can you help me on this.

I will create a separate issue about testing pypu deployment. This PR keeps growing and has some important improvements/fixes. I would like to merge this if you (@sverhoeven and @jspaaks ) agree.

**Comment by jspaaks** [comment]
Yes please merge before it gets too big!

**Comment by sverhoeven** [comment]
Agree, pypi can be done in another PR

**Pull request merged**
