### PR TITLE
Adds Sonar analysis to GH action

### LINKED ISSUE #9: Add code analysis tool
Add Codacy or similar tools for code analysis. 

Some options are listed in https://github.com/NLeSC/template

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #9
Refs #94

### CODE REVIEW

**Comment by sverhoeven** [comment]
Was able to run analysis locally with own token using `SONAR_TOKEN=xxxxxxxxxxxxx ~/sonar-scanner-3.1.0.1141/bin/sonar-scanner` of which the results can be seen at https://sonarcloud.io/dashboard?id=matchms_matchms

**Comment by sverhoeven** [comment]
Waiting for SONAR_TOKEN to be configured to make the checks green

**Comment by sverhoeven** [comment]
OK, now sonar analysis works correctly on ubuntu only.

**Comment by fdiblen** [comment]
@sverhoeven This looks complete to me. Can we close this?

**Review by fdiblen — APPROVED** [review]
Well done :100:

**Comment by jspaaks** [comment]
Can we somehow avoid calculating coverage locally? It breaks my pycharm's breakpoints (#130)

**Comment by sverhoeven** [comment]
I removed the `--cov ..` from setup.cfg and added it to GH action, but adding `--no-cov` to setup.cfg blocks coverage from being turned on via cli.

@jspaaks Could you test if pycharms breakpoints work now?

**Comment by jspaaks** [comment]
Yay the breakpoints work https://github.com/matchms/matchms/pull/149#issuecomment-618471878

**Review by jspaaks — APPROVED** [review]

**Pull request merged**
