### PR TITLE
Read the docs tweaks

### PR DESCRIPTION
**Pull request by sverhoeven**
* Added short description to homepage and API to table of contents
* Added link to GitHub
* Added intersphinx, to link types to other doc sites
* Enabled parsing of docstring in Numpy or Google format
* Dont render undocumented members
* Added documentation coverage reporting to GH Action, refs #137
* Removed unused _static

### CODE REVIEW

**Comment by sverhoeven** [comment]
Rendered at https://matchms.readthedocs.io/en/rtfd-tweaks/

**Comment by fdiblen** [comment]
Related to #157 and need discussion.

**Comment by sverhoeven** [comment]
Added threshold for number of undocumented threshold of 25.

**Comment by sverhoeven** [comment]
Functionality of #157 has been incorporated into this PR. So #157 is not needed anymore.

@fdiblen Could you review again?

**Review by fdiblen — APPROVED** [review]
Well done.

**Pull request merged**
