### PR TITLE
Import and export from and to json

### PR DESCRIPTION
**Pull request by florian-huber**
[EDIT] this PR became to big, so I split off one part which now has become PR #224 !
- Addressing #153 (now includes that GNPS partly shifted form mgf to json as well).
- The functions should be able to import spectrums from GNPS json files (https://gnps-external.ucsd.edu/gnpslibrary). This requires some parsing, because the metadata field names are different. 
- 1. GNPS json files contain a single value as string in ``Precursor_MZ`` instead of a float tuple in a ``pepmass`` field as pyteomics  --> #210 . I hence added a ``harmonize_precursor_mz`` filter.
- 2. GNPS json also contain the charge as a string field. I added this to our ``make_charge_scalar`` filter.
- Needs tests for loading and saving json.

(moved to #224: Integration test failed due to #211  (no losses included) --> I retrained the test model and changed the integration test.)

### CODE REVIEW

**Comment by fdiblen** [comment]
@florian-huber is this ready to review?

**Comment by florian-huber** [comment]
@fdiblen yes, a review would be great. Two workflow tests are still failing. They could be fixed temporarily by commenting out ``add_losses``, or by providing a new, retrained model.

**Comment by florian-huber** [comment]
@fdiblen I now also added a retrained model (which properly includes loss-words) to fix the broken integration test. 
(and it thereby also grew into a too big PR...)

**Comment by fdiblen** [comment]
@florian-huber could you fix coverage as well?

**Comment by florian-huber** [comment]
@fdiblen yes I will take care of that. But I anyway expect that I will remodel this PR quiet a bit, because it relies on other open PRs and I am also checking with Ming from GNPS if they provide any json schema we could adapt (I fear not, but who knows).

**Comment by jspaaks** [comment]
PR moved https://github.com/matchms/matchms/pull/32

**Pull request closed without merging**
