### PR TITLE
add editable logo and fix alias issues with edge of logo

### PR DESCRIPTION
**Pull request by cwmeijer**
- Logo improved on edges. Old logo was really choppy and aliased on the edges of the black outline. In the new version the edges are sharp. Other than that, the logo is identical.
- Also added the editable file of the logo with layers etc so someone can change it later on if they like. Note that the file is 'big' at 3-4 MB but I think that's ok.

### CODE REVIEW

**Comment by sverhoeven** [comment]
png logo looks cleaner, but has 1920x1080 res, which causes a lot of white space around the logo on https://github.com/matchms/matchms/tree/editable-logo-and-anti-alias . Can you re-export the png without padding?

**Comment by sverhoeven** [comment]
Cool, now I can see it without having to zoom in.

**Comment by cwmeijer** [comment]
Thanks, cropped it to content now.

**Comment by cwmeijer** [comment]
merge&close then?

**Review by sverhoeven — APPROVED** [review]
Looks good to me

**Pull request merged**
