### PR TITLE
More badges

### PR DESCRIPTION
**Pull request by jspaaks**
- added a ci badge
- added a readthedocs badge (assuming the docs are going to end up there)

Refs: https://github.com/matchms/matchms/issues/18
Notify:  @CunliangGeng, @fdiblen

### CODE REVIEW

**Comment by fdiblen** [comment]
@jspaaks CI status is unknow. Do you know why that happens?

**Comment by jspaaks** [comment]
@fdiblen That is because matchms currently does not have a presence on readthedocs.

**Comment by jspaaks** [comment]
badges

Maybe you are seeing something different than what I'm seeing?

**Review by CunliangGeng — APPROVED** [review]
Thanks, LGTM, you can merge it now.

**Comment by jspaaks** [comment]
image

I had to look it up ...so old.

**Pull request merged**
